yolo_model:

  config_file:
    name: yolov2-tiny_verification.cfg
  weight_file:
    name: yolov2-tiny_final_verification.weights
  threshold:
    value: 0.45
  detection_classes:
    names:
      - almiunium
      - handlight
      - mineralwater
      - orange_cookie
      - toy_garagara
      - yellow_cokkies
      - brownpail
      - hedgehog
      - oolongtea
      - plant
      - toy_tyutyu
