yolo_model:

  config_file:
    name: yolov3_verification.cfg
  weight_file:
    name: yolov3_verification.weights
  threshold:
    value: 0.50
  detection_classes:
    names:
      - almiunium
      - handlight
      - mineralwater
      - orangecookies
      - toygaragara
      - yellowcookies
      - brownpail
      - hedgehog
      - oolongtea
      - plant
      - toytyutyu
