footprint: [[-0.7, -0.35], [-0.7, 0.35], [0.5, 0.35], [0.5, -0.35]]
footprint_padding: 0.01

global_frame: /map
robot_base_frame: base_footprint

transform_tolerance: 0.5
update_frequency: 4.0
publish_frequency: 3.0

#layer definitions
static:
  map_topic: /map
  subscribe_to_updates: true

obstacles_laser:
  observation_sources: laser
  laser: {sensor_frame: velodyne, data_type: LaserScan, topic: /scan, clearing: true, marking: true, inf_is_valid: true}

inflation:
  inflation_radius: 2.0
  cost_scaling_factor: 10.0
